name: Release
on:
  push:
    branches:
      - main
      - feat/action-*

jobs:
  cross-test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync node version and setup cache
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'npm' # Set this to npm, yarn or pnpm.

      - name: Install dependencies and Run Test
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: npm install && npm test # Change this to npm, yarn or pnpm.